### ISSUE TITLE
Heh!

### ISSUE THREAD

**Issue by Voskresenskyi-Serhii** [ceramicSoda/dotfiles#1]
https://github.com/ceramicSoda/dotfiles/blob/031a6d3d4ed115f4e31468d8d723c38a58b21863/i3/config#L17

It is unacceptable! what's wrong with your eyes? So much workspace on your laptop? 😵‍💫

**Comment by ceramicSoda** [comment]
I have almost the same DPI as you have, 14" and 1080p
Anyway I set borders back to 2px 
Scared to imagine what you'll tell when you find 32px padding for terminal :D
